# Generated by Django 5.0.2 on 2024-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_qcstock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode_ID',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code_img/'),
        ),
    ]
