# Generated by Django 5.0.2 on 2024-03-02 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_transfernote_created_transfernote_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfernote',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
