# Generated by Django 5.0.2 on 2024-03-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_allocatedlocation_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedlocation',
            name='product',
        ),
    ]
