# Generated by Django 5.0.2 on 2024-03-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_allocatedlocation_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocatedlocation',
            old_name='available_quantity',
            new_name='balance_quantity',
        ),
    ]
