# Generated by Django 5.0.2 on 2024-03-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_available_quantity_allocatedlocation_balance_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocatedlocation',
            old_name='balance_quantity',
            new_name='quantity',
        ),
    ]
