# Generated by Django 5.0.2 on 2024-03-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_shipment_shipmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
