# Generated by Django 5.0.2 on 2024-03-02 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_shipment_shipment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentitem',
            name='product',
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='warehousestock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.warehousestock'),
            preserve_default=False,
        ),
    ]
