# Generated by Django 5.0.2 on 2024-03-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_gatepass_gate_pass_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='gate_pass_number',
            field=models.UUIDField(auto_created=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
