# Generated by Django 5.0.2 on 2024-03-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_gatepass_gate_pass_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='gate_pass_number',
            field=models.UUIDField(auto_created=True, blank=True, editable=False, null=True),
        ),
    ]
